// Code generated by "stringer -type=dbValueType"; DO NOT EDIT.

package rashdb

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[dbValueStr-0]
	_ = x[dbValueF32-1]
	_ = x[dbValueF64-2]
	_ = x[dbValueI8-3]
	_ = x[dbValueI32-4]
	_ = x[dbValueI64-5]
	_ = x[dbValueU8-6]
	_ = x[dbValueU32-7]
	_ = x[dbValueU64-8]
}

const _dbValueType_name = "dbValueStrdbValueF32dbValueF64dbValueI8dbValueI32dbValueI64dbValueU8dbValueU32dbValueU64"

var _dbValueType_index = [...]uint8{0, 10, 20, 30, 39, 49, 59, 68, 78, 88}

func (i dbValueType) String() string {
	if i >= dbValueType(len(_dbValueType_index)-1) {
		return "dbValueType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _dbValueType_name[_dbValueType_index[i]:_dbValueType_index[i+1]]
}
