// Code generated by "stringer -type=dbValueType"; DO NOT EDIT.

package rashdb

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[dbStr-0]
	_ = x[dbInt-1]
	_ = x[dbReal-2]
	_ = x[dbNull-3]
	_ = x[dbText-4]
	_ = x[dbBlob-5]
}

const _dbValueType_name = "dbStrdbIntdbRealdbNulldbTextdbBlob"

var _dbValueType_index = [...]uint8{0, 5, 10, 16, 22, 28, 34}

func (i dbValueType) String() string {
	if i >= dbValueType(len(_dbValueType_index)-1) {
		return "dbValueType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _dbValueType_name[_dbValueType_index[i]:_dbValueType_index[i+1]]
}
