// Code generated by "stringer -type=DataType"; DO NOT EDIT.

package disk

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DBStr-0]
	_ = x[DBInt-1]
	_ = x[DBReal-2]
	_ = x[DBNull-3]
	_ = x[DBText-4]
	_ = x[DBBlob-5]
}

const _DataType_name = "DBStrDBIntDBRealDBNullDBTextDBBlob"

var _DataType_index = [...]uint8{0, 5, 10, 16, 22, 28, 34}

func (i DataType) String() string {
	if i >= DataType(len(_DataType_index)-1) {
		return "DataType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DataType_name[_DataType_index[i]:_DataType_index[i+1]]
}
